config/routes.rb
require 'resque/server'
Burst::Application.routes.draw do
  resources :user_position_metrics

  resources :user_position_metric_points

  match '/auth/:provider/callback' => 'sessions#create'
  match '/signout' => 'sessions#destroy', as: :signout
  match '/auth/failure' => 'sessions#fail'

  root :to => 'articles#index'
  resources :articles
  resources :users  
  mount Resque::Server.new, :at => "/resque"
  post '/' => 'articles#index', as: :filter_articles
  
end

app/models/user_position_metric_point.rb
class UserPositionMetricPoint < ActiveRecord::Base
  belongs_to :user_position_metric
  belongs_to :user
end

app/controllers/user_position_metric_points_controller.rb
class UserPositionMetricPointsController < ApplicationController
  # GET /user_position_metric_points
  # GET /user_position_metric_points.json
  def index
    @user_position_metric_points = UserPositionMetricPoint.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user_position_metric_points }
    end
  end

  # GET /user_position_metric_points/1
  # GET /user_position_metric_points/1.json
  def show
    @user_position_metric_point = UserPositionMetricPoint.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_position_metric_point }
    end
  end

  # GET /user_position_metric_points/new
  # GET /user_position_metric_points/new.json
  def new
    @user_position_metric_point = UserPositionMetricPoint.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_position_metric_point }
    end
  end

  # GET /user_position_metric_points/1/edit
  def edit
    @user_position_metric_point = UserPositionMetricPoint.find(params[:id])
  end

  # POST /user_position_metric_points
  # POST /user_position_metric_points.json
  def create
    @user_position_metric_point = UserPositionMetricPoint.new(params[:user_position_metric_point])

    respond_to do |format|
      if @user_position_metric_point.save
        format.html { redirect_to @user_position_metric_point, notice: 'User position metric point was successfully created.' }
        format.json { render json: @user_position_metric_point, status: :created, location: @user_position_metric_point }
      else
        format.html { render action: "new" }
        format.json { render json: @user_position_metric_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_position_metric_points/1
  # PUT /user_position_metric_points/1.json
  def update
    @user_position_metric_point = UserPositionMetricPoint.find(params[:id])

    respond_to do |format|
      if @user_position_metric_point.update_attributes(params[:user_position_metric_point])
        format.html { redirect_to @user_position_metric_point, notice: 'User position metric point was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_position_metric_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_position_metric_points/1
  # DELETE /user_position_metric_points/1.json
  def destroy
    @user_position_metric_point = UserPositionMetricPoint.find(params[:id])
    @user_position_metric_point.destroy

    respond_to do |format|
      format.html { redirect_to user_position_metric_points_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/user_position_metric_points_helper.rb
module UserPositionMetricPointsHelper
end

app/views/user_position_metric_points/_form.html.erb
<%= form_for(@user_position_metric_point) do |f| %>
  <% if @user_position_metric_point.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_position_metric_point.errors.count, "error") %> prohibited this user_position_metric_point from being saved:</h2>

      <ul>
      <% @user_position_metric_point.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :key %><br />
    <%= f.text_field :key %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :user_position_metric_id %><br />
    <%= f.number_field :user_position_metric_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_position_metric_points/edit.html.erb
<h1>Editing user_position_metric_point</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_position_metric_point %> |
<%= link_to 'Back', user_position_metric_points_path %>

app/views/user_position_metric_points/index.html.erb
<h1>Listing user_position_metric_points</h1>

<table>
  <tr>
    <th>Key</th>
    <th>Value</th>
    <th>User position metric</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_position_metric_points.each do |user_position_metric_point| %>
  <tr>
    <td><%= user_position_metric_point.key %></td>
    <td><%= user_position_metric_point.value %></td>
    <td><%= user_position_metric_point.user_position_metric_id %></td>
    <td><%= user_position_metric_point.user_id %></td>
    <td><%= link_to 'Show', user_position_metric_point %></td>
    <td><%= link_to 'Edit', edit_user_position_metric_point_path(user_position_metric_point) %></td>
    <td><%= link_to 'Destroy', user_position_metric_point, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User position metric point', new_user_position_metric_point_path %>

app/views/user_position_metric_points/new.html.erb
<h1>New user_position_metric_point</h1>

<%= render 'form' %>

<%= link_to 'Back', user_position_metric_points_path %>

app/views/user_position_metric_points/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Key:</b>
  <%= @user_position_metric_point.key %>
</p>

<p>
  <b>Value:</b>
  <%= @user_position_metric_point.value %>
</p>

<p>
  <b>User position metric:</b>
  <%= @user_position_metric_point.user_position_metric_id %>
</p>

<p>
  <b>User:</b>
  <%= @user_position_metric_point.user_id %>
</p>


<%= link_to 'Edit', edit_user_position_metric_point_path(@user_position_metric_point) %> |
<%= link_to 'Back', user_position_metric_points_path %>