config/routes.rb
require 'resque/server'
Burst::Application.routes.draw do
  resources :user_position_metrics

  resources :user_position_metric_points

  match '/auth/:provider/callback' => 'sessions#create'
  match '/signout' => 'sessions#destroy', as: :signout
  match '/auth/failure' => 'sessions#fail'

  root :to => 'articles#index'
  resources :articles
  resources :users  
  mount Resque::Server.new, :at => "/resque"
  post '/' => 'articles#index', as: :filter_articles
  
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :importance_metric_points
  has_many :position_metric_points
  belongs_to :source
  
  def self.sorted_articles(params)
    @articles = self.where(:created_at => (Time.now-params[:end].to_i)..(Time.now-params[:start].to_i))
    return [@articles, {}] if @articles.empty?
    @oldest = @articles.sort{|x,y| x.created_at<=>y.created_at}.first
    params[:oldtime] = @oldest.created_at.to_time.to_i
    @newest = @articles.sort{|x,y| x.created_at<=>y.created_at}.last
    params[:newtime] = @newest.created_at.to_time.to_i
    params[:range] = params[:newtime] - params[:oldtime]
    params[:importance_metric_points] = ImportanceMetricPoint.where(:article_id => @articles.collect(&:id))
    params[:importance_metrics] = ImportanceMetric.where(:id => params[:importance_metric_points].collect(&:importance_metric_id).uniq)
    params[:user_position_metric_points] = UserPositionMetricPoint.where(:user_id => params[:user_id])
    params[:user_position_metrics] = UserPositionMetric.where(:id => params[:user_position_metric_points].collect(&:user_position_metric_id).uniq)
    params[:position_metric_points] = PositionMetricPoint.where(:article_id => @articles.collect(&:id))
    params[:position_metrics] = PositionMetric.where(:id => params[:position_metric_points].collect(&:position_metric_id).uniq)
    params = ImportanceMetric.precalculate_distributions(@articles, params)
    params = UserPositionMetric.precalculate_distributions(@articles, params)
    params[:articles] = @articles
    scores = {}
    @articles.collect{|x| scores[x.id] = x.score(params)}
    [@articles.sort{|x,y| scores[x.id]<=>scores[y.id]}.reverse, scores]
  end
  
  def importances
    importance_metric_points
  end

  def positions
    position_metric_points
  end
  
  def score(params)
    return (importance_score(params)+proximity_score(params)+time_score(params))/3
  end
  
  def importance_score(params)
    sum = 0
    count = 0.0
    params[:importance_metrics].each do |importance_metric|
      sum+=importance_metric.calculate_sub_score(self, params)
      count+=1
    end
    return (sum/count)*(params[:importance]/100.0)
  end
  
  def proximity_score(params)
    if params[:user_id] == 0
      return 0
    else
      sum = 0
      count = 0.0
      params[:user_position_metrics].each do |position_metric|
        sum+=position_metric.calculate_sub_score(self, params)
        count+=1
      end
      return (sum/count)*(params[:proximity]/100.0)
    end
  end
  
  def time_score(params)
    @actual = self.created_at.to_f
    return ((params[:range].to_f - (params[:newtime] - @actual)) / params[:range])*(params[:time_salience]/100.0)
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.json
  def index
    if current_user
      params[:start] = (params[:start]&&params[:start].to_f-60*60*24*7*4) || 0
      params[:end] = (params[:end]&&params[:end].to_f-60*60*24*7*4) || 3600*24*7*4
      params[:time_salience] = 100
      params[:importance] = (params[:importance]&&params[:importance].to_f) || 100
      params[:proximity] = (params[:proximity]&&params[:proximity].to_f) || 100
      params[:user_id] = (current_user&&current_user.id) || 0
      @articles, @scores = Article.sorted_articles(params)
    else
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :abstract %><br />
    <%= f.text_area :abstract %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br />
    <%= f.datetime_select :created_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/_slider.html.slim
.row
  .span12
    = form_tag(filter_articles_path, id: 'filter-results') do
      fieldset
        .control-group
          #time-slider
          h3.align-center#time_output Time: #{exact_time(params[:end].to_i-params[:start].to_i || 3600)}
          = hidden_field_tag :start, params[:start] || 0
          = hidden_field_tag :end, params[:end] || 3600*24*7*4
          //#time-salience-slider
          //h3.align-center#time_salience_output Time Importance: #{percentage(params[:time_salience].to_i || 100)}
          //= hidden_field_tag :time_salience, params[:time_salience] || 100
          #importance-slider
          h3.align-center#importance_output Popularity: #{percentage(params[:importance].to_i || 100)}
          = hidden_field_tag :importance, params[:importance] || 100
          #proximity-slider
          h3.align-center#proximity_output Closeness: #{percentage(params[:proximity].to_i || 100)}
          = hidden_field_tag :proximity, params[:proximity] || 100

          .form-actions.align-center
            p
              = submit_tag 'Filter', class: 'btn btn-primary'
            p = link_to 'Back', '#', id: 'back-to-new-curation', class: 'btn'

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<% if current_user %>
<div class="row">
  <% last_span = 0;count=0;counts=[0,3,7,13];spans=[12,4,4,4,3,3,3,3,2,2,2,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1];spans.each do |span| %>
    <% article = @articles[count]%>
    <% if article %>
      <span class="span<%= span %> article<%= span %>">
        <% if span == 12 %>
        <h2><a href="<%= article.url %>"><%= article.title %></a><span class="score" style="color:<%= cycle("#be5122", "#e7302a", "#e9501e", "#f39200", "#f9b233", "#ffdd0e", "#f8ea1b") %>"><%= (@scores[article.id].to_f.round(2)*100).to_i %>% Match</span></h2>
        <span class="stats"><%= article.created_at.strftime("%b, %d, %Y, at %H:%M") %> </span>
        <p><img src="<%= Setting.find_by_key("logo").actual_value %>" width="20" height="20" alt=""><%= article.abstract %></p>
        <div class="nav-list"></div>
        <% elsif span == 2 %>
          <h2><a href="<%= article.url %>"><%= article.title %></a></h2>

          <img src="<%= Setting.find_by_key("logo").actual_value %>" width="20" height="20" alt="">
          <span class="score" style="color:<%= cycle("#be5122", "#e7302a", "#e9501e", "#f39200", "#f9b233", "#ffdd0e", "#f8ea1b") %>"><%= (@scores[article.id].to_f.round(2)*100).to_i %>%</span>
        <% elsif span > 2 %>
          <h2><a href="<%= article.url %>"><%= article.title %></a></h2>
          
        <span class="stats"><%= article.created_at.strftime("%b, %d, %Y, at %H:%M") %> <span class="score" style="color:<%= cycle("#be5122", "#e7302a", "#e9501e", "#f39200", "#f9b233", "#ffdd0e", "#f8ea1b") %>"><%= (@scores[article.id].to_f.round(2)*100).to_i %>%</span><br /></span>
        <p><img src="<%= Setting.find_by_key("logo").actual_value %>" width="20" height="20" alt=""><%= article.abstract %></p>
        <div class="nav-list"></div>
        <% elsif span == 2 %>
          <img src="<%= Setting.find_by_key("logo").actual_value %>" width="20" height="20" alt="">
          <span class="score" style="color:<%= cycle("#be5122", "#e7302a", "#e9501e", "#f39200", "#f9b233", "#ffdd0e", "#f8ea1b") %>"><%= (@scores[article.id].to_f.round(2)*100).to_i %>%</span>
        <% else %>
        <h2><%= article.title %></h2>
        <% end %>
      </span>
      <% if counts.include?(count)%>
        </div>
        <hr />
        <div class="row">
      <% end %>
      <%count+=1%>
    <% end %>
  <% end %>
</div>
<%= render :partial => 'slider'%>
<% else %>
<% end %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @article.title %>
</p>

<p>
  <b>Url:</b>
  <%= @article.url %>
</p>

<p>
  <b>Abstract:</b>
  <%= @article.abstract %>
</p>

<p>
  <b>Created at:</b>
  <%= @article.created_at %>
</p>


<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>