config/routes.rb
require 'resque/server'
Burst::Application.routes.draw do
  resources :user_position_metrics

  resources :user_position_metric_points

  match '/auth/:provider/callback' => 'sessions#create'
  match '/signout' => 'sessions#destroy', as: :signout
  match '/auth/failure' => 'sessions#fail'

  root :to => 'articles#index'
  resources :articles
  resources :users  
  mount Resque::Server.new, :at => "/resque"
  post '/' => 'articles#index', as: :filter_articles
  
end

app/models/position_metric.rb
class PositionMetric < ActiveRecord::Base
  has_many :position_metric_points
end

app/controllers/position_metrics_controller.rb
class PositionMetricsController < ApplicationController
  # GET /position_metrics
  # GET /position_metrics.json
  def index
    @position_metrics = PositionMetric.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @position_metrics }
    end
  end

  # GET /position_metrics/1
  # GET /position_metrics/1.json
  def show
    @position_metric = PositionMetric.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @position_metric }
    end
  end

  # GET /position_metrics/new
  # GET /position_metrics/new.json
  def new
    @position_metric = PositionMetric.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @position_metric }
    end
  end

  # GET /position_metrics/1/edit
  def edit
    @position_metric = PositionMetric.find(params[:id])
  end

  # POST /position_metrics
  # POST /position_metrics.json
  def create
    @position_metric = PositionMetric.new(params[:position_metric])

    respond_to do |format|
      if @position_metric.save
        format.html { redirect_to @position_metric, notice: 'Position metric was successfully created.' }
        format.json { render json: @position_metric, status: :created, location: @position_metric }
      else
        format.html { render action: "new" }
        format.json { render json: @position_metric.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /position_metrics/1
  # PUT /position_metrics/1.json
  def update
    @position_metric = PositionMetric.find(params[:id])

    respond_to do |format|
      if @position_metric.update_attributes(params[:position_metric])
        format.html { redirect_to @position_metric, notice: 'Position metric was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @position_metric.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /position_metrics/1
  # DELETE /position_metrics/1.json
  def destroy
    @position_metric = PositionMetric.find(params[:id])
    @position_metric.destroy

    respond_to do |format|
      format.html { redirect_to position_metrics_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/position_metrics_helper.rb
module PositionMetricsHelper
end

app/views/position_metrics/_form.html.erb
<%= form_for(@position_metric) do |f| %>
  <% if @position_metric.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@position_metric.errors.count, "error") %> prohibited this position_metric from being saved:</h2>

      <ul>
      <% @position_metric.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/position_metrics/edit.html.erb
<h1>Editing position_metric</h1>

<%= render 'form' %>

<%= link_to 'Show', @position_metric %> |
<%= link_to 'Back', position_metrics_path %>

app/views/position_metrics/index.html.erb
<h1>Listing position_metrics</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @position_metrics.each do |position_metric| %>
  <tr>
    <td><%= link_to 'Show', position_metric %></td>
    <td><%= link_to 'Edit', edit_position_metric_path(position_metric) %></td>
    <td><%= link_to 'Destroy', position_metric, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Position metric', new_position_metric_path %>

app/views/position_metrics/new.html.erb
<h1>New position_metric</h1>

<%= render 'form' %>

<%= link_to 'Back', position_metrics_path %>

app/views/position_metrics/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_position_metric_path(@position_metric) %> |
<%= link_to 'Back', position_metrics_path %>