config/routes.rb
require 'resque/server'
Burst::Application.routes.draw do
  resources :user_position_metrics

  resources :user_position_metric_points

  match '/auth/:provider/callback' => 'sessions#create'
  match '/signout' => 'sessions#destroy', as: :signout
  match '/auth/failure' => 'sessions#fail'

  root :to => 'articles#index'
  resources :articles
  resources :users  
  mount Resque::Server.new, :at => "/resque"
  post '/' => 'articles#index', as: :filter_articles
  
end

app/models/position_metric_point.rb
class PositionMetricPoint < ActiveRecord::Base
  belongs_to :position_metric
  belongs_to :article
end

app/controllers/position_metric_points_controller.rb
class PositionMetricPointsController < ApplicationController
  # GET /position_metric_points
  # GET /position_metric_points.json
  def index
    @position_metric_points = PositionMetricPoint.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @position_metric_points }
    end
  end

  # GET /position_metric_points/1
  # GET /position_metric_points/1.json
  def show
    @position_metric_point = PositionMetricPoint.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @position_metric_point }
    end
  end

  # GET /position_metric_points/new
  # GET /position_metric_points/new.json
  def new
    @position_metric_point = PositionMetricPoint.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @position_metric_point }
    end
  end

  # GET /position_metric_points/1/edit
  def edit
    @position_metric_point = PositionMetricPoint.find(params[:id])
  end

  # POST /position_metric_points
  # POST /position_metric_points.json
  def create
    @position_metric_point = PositionMetricPoint.new(params[:position_metric_point])

    respond_to do |format|
      if @position_metric_point.save
        format.html { redirect_to @position_metric_point, notice: 'Position metric point was successfully created.' }
        format.json { render json: @position_metric_point, status: :created, location: @position_metric_point }
      else
        format.html { render action: "new" }
        format.json { render json: @position_metric_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /position_metric_points/1
  # PUT /position_metric_points/1.json
  def update
    @position_metric_point = PositionMetricPoint.find(params[:id])

    respond_to do |format|
      if @position_metric_point.update_attributes(params[:position_metric_point])
        format.html { redirect_to @position_metric_point, notice: 'Position metric point was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @position_metric_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /position_metric_points/1
  # DELETE /position_metric_points/1.json
  def destroy
    @position_metric_point = PositionMetricPoint.find(params[:id])
    @position_metric_point.destroy

    respond_to do |format|
      format.html { redirect_to position_metric_points_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/position_metric_points_helper.rb
module PositionMetricPointsHelper
end

app/views/position_metric_points/_form.html.erb
<%= form_for(@position_metric_point) do |f| %>
  <% if @position_metric_point.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@position_metric_point.errors.count, "error") %> prohibited this position_metric_point from being saved:</h2>

      <ul>
      <% @position_metric_point.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/position_metric_points/edit.html.erb
<h1>Editing position_metric_point</h1>

<%= render 'form' %>

<%= link_to 'Show', @position_metric_point %> |
<%= link_to 'Back', position_metric_points_path %>

app/views/position_metric_points/index.html.erb
<h1>Listing position_metric_points</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @position_metric_points.each do |position_metric_point| %>
  <tr>
    <td><%= link_to 'Show', position_metric_point %></td>
    <td><%= link_to 'Edit', edit_position_metric_point_path(position_metric_point) %></td>
    <td><%= link_to 'Destroy', position_metric_point, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Position metric point', new_position_metric_point_path %>

app/views/position_metric_points/new.html.erb
<h1>New position_metric_point</h1>

<%= render 'form' %>

<%= link_to 'Back', position_metric_points_path %>

app/views/position_metric_points/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_position_metric_point_path(@position_metric_point) %> |
<%= link_to 'Back', position_metric_points_path %>